version: "3"
services:
  factorio-server:
    image: hjfmailbox/factorio-server:1.1.42
    container_name: factorio-server
    #restart: always
    environment:
      - PUID=845
      - PGID=845
      - UPDATE_MODS_ON_START=false
      - USERNAME=
      - TOKEN=
      - PORT=34197    
    volumes:
      - ./factorio/saves:/factorio/saves
      - ./factorio/config:/factorio/config
      - ./factorio/mods:/factorio/mods
      - ./factorio/server-settings.json:/factorio/server-settings.json
    ports:
     - "34197:34197/udp"
     - "27015:27015/tcp"
